
# docker-compose.yaml
version: '3'

services:
  a9db:
    image: postgres:12
    container_name: ShopOnline
    restart: always
    network_mode: "bridge"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: ShopOnline
    ports:
      - "5432:5432"

volumes:
  db_data:
